name: Java CI

on: [push]

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8 & run tests & generate artifacts
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - id: shortrev
      run: echo ::set-output name=rev::$(git rev-parse --short HEAD)
    - id: pversion
      run: echo ::set-output name=ver::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8 & run tests & generate artifacts
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: mvn -B clean test install -Dgroups="test"
    - name: Version set
      run: mvn versions:set versions:commit -DnewVersion=${{ steps.pversion.outputs.rev }}-${{ steps.shortrev.outputs.ver }}
    - name: PMD check
      run: mvn pmd:check
    - id: getfilename
      run: echo "::set-output name=file::$(ls target/symphony-dal-communicator-cisco-[0-9].[0-9].[0-9]-[.+?].jar)"
    - uses: actions/upload-artifact@v1
      with:
        name: Cisco
        path: ${{ steps.getfilename.outputs.file }}